server:
  port: 8081
# Spring Boot configuration
spring:
  main:
    allow-circular-references: true
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/callboardBase
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    resources:
      static-locations: [ classpath:/resources/, classpath:/static/ ]
      chain:
        strategy:
          content:
            paths: /**
            enabled: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#          starttls:
#            enable: true
#            required: true
#    username: maksimdovydenko1@gmail1.com
#    password: Maksim777
#  cache:
#    type: NONE